USE bamazon;

CREATE TABLE departments(
	department_id	BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	department_name	VARCHAR(50) NOT NULL,
	department_desc	VARCHAR(250),
	over_head_cost	FLOAT
);

CREATE TABLE products(
	item_id 		BIGINT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT PRIMARY KEY,
	product_name	VARCHAR(50) NOT NULL,
	department_id	BIGINT UNSIGNED NOT NULL,
	price			FLOAT NOT NULL DEFAULT 0.0,
	stock_quantity	INTEGER UNSIGNED NOT NULL DEFAULT 0,
	FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

CREATE TABLE users(
	user_id		BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	login_id	VARCHAR(15) UNIQUE NOT NULL,
	f_name		VARCHAR(30),
	l_name		VARCHAR(30),
	password	VARCHAR(30) NOT NULL
);

CREATE TABLE roles(
	role_id		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	role_type	VARCHAR(3) UNIQUE NOT NULL,
	description	VARCHAR(50)
);

CREATE TABLE user_role(
	user_id	BIGINT UNSIGNED NOT NULL,
	role_id TINYINT UNSIGNED NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (role_id) REFERENCES roles(role_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY (user_id, role_id)
);

CREATE TABLE orders(
	order_id	BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id		BIGINT UNSIGNED NOT NULL,
	timeplaced	TIMESTAMP NOT NULL,
	status		VARCHAR(10) NOT NULL,
	total		FLOAT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE order_items(
	order_id	BIGINT UNSIGNED NOT NULL,
	item_id		BIGINT UNSIGNED NOT NULL,
	price		FLOAT NOT NULL,
	quantity	INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (order_id, item_id),
	FOREIGN KEY (order_id) REFERENCES orders(order_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (item_id) REFERENCES products(item_id) ON UPDATE CASCADE ON DELETE RESTRICT
);
	